# 𝓒𝓸𝓭𝓮𝓭 𝓫𝔂 𝓔𝔁𝓸𝓼𝓶𝓲𝓾𝓶 (vk.com/prodbyhakin)
# Спасибо, что используете мой плагин!

# Настройка сообшений при смерти
# Доступен плейсхолдер %player% т.е. игрок
Die:
  groups:
    default:
      # Любые команды
      commands:
        - "say &cНу ты дурак, %player%"
        - "say &cТак тупо слился!"
      message: "&c(&li&c)&f Вы умерли!"
      actionbar-message: "&aВы умерли и потеряли &c&l5 касарей!"
    ric:
      # Любые команды
      commands:
        - "say &cНу ты дурак!"
        - "say &cТак тупо слился!"
      message: "&c(&li&c)&f Вы умерли! Но вы рыцарь поэтому потеряли меньше!"
      actionbar-message: "&a Вы умерли и потеряли &c&l касарей!"


# Настройка сообшений при убийстве другим игроком
# Доступные плейсхолдеры:
# %target% цель убийства, %killer% убийца
Kill:
  groups:
    default:
      commands:
        - "eco remove %target% 300"
        - "eco give %killer% 300"
      target:
        message: "&c(&li&c)&f Вас убил &7%killer%&f и забрал &730 касарей!"
        actionbar-message: "&4&lВас убили!"
      killer:
        message: "&c(&li&c)&f Вы убили &e%killer%&f и забрали &730 касарей!"
        actionbar-message: "&b&lВы убили!"
    ric:
      commands:
        - "eco remove %target% 600"
        - "eco give %killer% 600"
      target:
        message: "&c(&li&c)&f Вас убил &7%killer%&f и забрал &760 касарей!"
        actionbar-message: "&4&lВас убили!"
      killer:
        message: "&c(&li&c)&f Вы убили &e%killer%&f и забрали &760 касарей!"
        actionbar-message: "&b&lВы убили!"
# Рыцарь убивает дефолта
# И забирает у него на 50% больше
# чем если бы дефолт убил дефолта